apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.10.47"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.10.47"
          digest: "sha256:1c5b14c967fe81f5208f2e73d70d5720da5136c4c98ec24a44b757378d2804a9"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.10.47"
          digest: "sha256:1c5b14c967fe81f5208f2e73d70d5720da5136c4c98ec24a44b757378d2804a9"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.10.47"
          target-environment: "QA"

