apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.09.54"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.09.54"
          digest: "sha256:2372e13a5ea7b1a3b6b02f89487681469efd3c9ee939057ecf9294c9730afc0d"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.09.54"
          digest: "sha256:2372e13a5ea7b1a3b6b02f89487681469efd3c9ee939057ecf9294c9730afc0d"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.09.54"
          target-environment: "QA"

