apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.12.58"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.12.58"
          digest: "sha256:af17a0e99728cd684fcf01db6cf9b382acd673f368b5e5880a1c2d08db2f206a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.12.58"
          digest: "sha256:af17a0e99728cd684fcf01db6cf9b382acd673f368b5e5880a1c2d08db2f206a"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.12.58"
          target-environment: "QA"

