apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.12.12"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.12.12"
          digest: "sha256:51336ed8429eefa6f38dc271f4b496e597835743c21fdf9e5c15a547d2122d32"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.12.12"
          digest: "sha256:51336ed8429eefa6f38dc271f4b496e597835743c21fdf9e5c15a547d2122d32"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.12.12"
          target-environment: "QA"

