apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.00.46"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.00.46"
          digest: "sha256:7afe98c1216dd1a20bc9979cc02a3c5d85879c4ad7f94c24471745b087991db0"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.00.46"
          digest: "sha256:7afe98c1216dd1a20bc9979cc02a3c5d85879c4ad7f94c24471745b087991db0"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.00.46"
          target-environment: "QA"

