apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.05.47"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.05.47"
          digest: "sha256:c1516aa7bdc9db379b0b72c66d53b92653076d4d8cf5a31cc8f6ae0b5434e2a6"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.05.47"
          digest: "sha256:c1516aa7bdc9db379b0b72c66d53b92653076d4d8cf5a31cc8f6ae0b5434e2a6"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.05.47"
          target-environment: "QA"

