apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.10.13"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.10.13"
          digest: "sha256:cb9d5d5a850dc317e8e709416e311173cf418c2ee3c8557c29307b306be4cde6"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.10.13"
          digest: "sha256:cb9d5d5a850dc317e8e709416e311173cf418c2ee3c8557c29307b306be4cde6"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.10.13"
          target-environment: "QA"

