apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.06.21"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.06.21"
          digest: "sha256:e9cc618ecf20687e32ae8a4ea8858e87bf3828716b85b3274d83a93c47136f64"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.06.21"
          digest: "sha256:e9cc618ecf20687e32ae8a4ea8858e87bf3828716b85b3274d83a93c47136f64"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.06.21"
          target-environment: "QA"

