apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.17"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.17"
          digest: "sha256:9338277bf13f1fd398be904e7237a70d402f8bf6df4c90611db2fb5311500621"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.17"
          digest: "sha256:9338277bf13f1fd398be904e7237a70d402f8bf6df4c90611db2fb5311500621"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.17"
          target-environment: "QA"

