apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.12.07"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.12.07"
          digest: "sha256:fcd566351ebfa420b520ffe62df9e8af8eb0fdcb4bfe18a2ad9a14fe9afab0c0"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.12.07"
          digest: "sha256:fcd566351ebfa420b520ffe62df9e8af8eb0fdcb4bfe18a2ad9a14fe9afab0c0"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.12.07"
          target-environment: "QA"

