apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.07.24"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.07.24"
          digest: "sha256:e5ab02d25a4c212afc033ff18783ff3349e0a50ac62d7cdd0ff3a44bd70ee1ac"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.07.24"
          digest: "sha256:e5ab02d25a4c212afc033ff18783ff3349e0a50ac62d7cdd0ff3a44bd70ee1ac"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.07.24"
          target-environment: "QA"

