apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.12.33"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.12.33"
          digest: "sha256:08633a5023a578d01e72eb4558c7fb31c624ea5331d3cbf2b758e40cb2d9e8fe"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.12.33"
          digest: "sha256:08633a5023a578d01e72eb4558c7fb31c624ea5331d3cbf2b758e40cb2d9e8fe"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.12.33"
          target-environment: "QA"

