apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "03.10.41"
          url: "docker.io/cbpautomation/python-hello-world-docker:03.10.41"
          digest: "sha256:edae83df4d221490fecf6e4790ccad05a670ce2d3e51c7c8ee9e1bcd17a8e068"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "03.10.41"
          digest: "sha256:edae83df4d221490fecf6e4790ccad05a670ce2d3e51c7c8ee9e1bcd17a8e068"
          url: "docker.io/cbpautomation/python-hello-world-docker:03.10.41"
          target-environment: "QA"

