apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "15.10.58"
          url: "docker.io/cbpautomation/python-hello-world-docker:15.10.58"
          digest: "sha256:8cf95c9332a81cea1ae171947c2d0deea86920b1bc291314e1cc99bc5b63acf2"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "15.10.58"
          digest: "sha256:8cf95c9332a81cea1ae171947c2d0deea86920b1bc291314e1cc99bc5b63acf2"
          url: "docker.io/cbpautomation/python-hello-world-docker:15.10.58"
          target-environment: "QA"

