apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "08.05.24"
          url: "docker.io/cbpautomation/python-hello-world-docker:08.05.24"
          digest: "sha256:a781a80f2286bc09bd646d1ca2fbe7bcbcfcb3d8ab23ba7bcfb0c6f730878f11"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "08.05.24"
          digest: "sha256:a781a80f2286bc09bd646d1ca2fbe7bcbcfcb3d8ab23ba7bcfb0c6f730878f11"
          url: "docker.io/cbpautomation/python-hello-world-docker:08.05.24"
          target-environment: "QA"

