apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.11.57"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.11.57"
          digest: "sha256:e7752ffccf054a793b5cb6d636c909cab3e668442490669e64ab5d8a782f2099"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.11.57"
          digest: "sha256:e7752ffccf054a793b5cb6d636c909cab3e668442490669e64ab5d8a782f2099"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.11.57"
          target-environment: "QA"

