apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.10.40"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.10.40"
          digest: "sha256:8218de91ea5c7833e8695fa9958702a14601a2ef16b6be3124ed27c2a726a96a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.10.40"
          digest: "sha256:8218de91ea5c7833e8695fa9958702a14601a2ef16b6be3124ed27c2a726a96a"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.10.40"
          target-environment: "QA"

