apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.21.55"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.21.55"
          digest: "sha256:80053334bd31be6fde93f47df2dc7bb77923c236b1b36e2787a66f3fa8f3886a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.21.55"
          digest: "sha256:80053334bd31be6fde93f47df2dc7bb77923c236b1b36e2787a66f3fa8f3886a"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.21.55"
          target-environment: "QA"

