apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.11.57"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.11.57"
          digest: "sha256:0bc6219531b807ff2115c736e9180248854c73adccf0ee7213eca847269afa58"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.11.57"
          digest: "sha256:0bc6219531b807ff2115c736e9180248854c73adccf0ee7213eca847269afa58"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.11.57"
          target-environment: "QA"

