apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.11.34"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.11.34"
          digest: "sha256:9f8d78b31f6bf4d5d210217253afcd1765151e42b37aeacdad15d28859aa8c9a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.11.34"
          digest: "sha256:9f8d78b31f6bf4d5d210217253afcd1765151e42b37aeacdad15d28859aa8c9a"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.11.34"
          target-environment: "QA"

