apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.23.58"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.23.58"
          digest: "sha256:b270db5a8beeac2084dfc8fd7b7bd38cc17e882dd53ae997368fdb796ca3657c"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.23.58"
          digest: "sha256:b270db5a8beeac2084dfc8fd7b7bd38cc17e882dd53ae997368fdb796ca3657c"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.23.58"
          target-environment: "QA"

