apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.23.56"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.23.56"
          digest: "sha256:1062ca87b7f64fe15f72202ff389906c73dd4d35edf580ae69f643d6ac9359a6"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.23.56"
          digest: "sha256:1062ca87b7f64fe15f72202ff389906c73dd4d35edf580ae69f643d6ac9359a6"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.23.56"
          target-environment: "QA"

