apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.11.48"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.11.48"
          digest: "sha256:9dd2b91e0458aad5c2035a68d78e381fc3cb09003553f5155290f28322681aa4"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.11.48"
          digest: "sha256:9dd2b91e0458aad5c2035a68d78e381fc3cb09003553f5155290f28322681aa4"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.11.48"
          target-environment: "QA"

