apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.10.36"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.10.36"
          digest: "sha256:04e9303820b87c39f8190813236f3d0b4f8cc8dad90d150f3a69d89eae71ee6b"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.10.36"
          digest: "sha256:04e9303820b87c39f8190813236f3d0b4f8cc8dad90d150f3a69d89eae71ee6b"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.10.36"
          target-environment: "QA"

