apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.39"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.39"
          digest: "sha256:3d9a613df9a34b930a564bf19fd41b3bcbd8765769b8cde58f3dd2c5ed7aa54f"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.39"
          digest: "sha256:3d9a613df9a34b930a564bf19fd41b3bcbd8765769b8cde58f3dd2c5ed7aa54f"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.39"
          target-environment: "QA"

