apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "01.10.47"
          url: "docker.io/cbpautomation/python-hello-world-docker:01.10.47"
          digest: "sha256:d68069c75e617ab0ed9e1960f6f27a5ffa1ed9b7532cda1471f2e95d23150bfa"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "01.10.47"
          digest: "sha256:d68069c75e617ab0ed9e1960f6f27a5ffa1ed9b7532cda1471f2e95d23150bfa"
          url: "docker.io/cbpautomation/python-hello-world-docker:01.10.47"
          target-environment: "QA"

