apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.14.22"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.14.22"
          digest: "sha256:3a45f5bf323a03c9197ba47ef950e04e3c042f7e555cb6e04f92e2f768037975"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.14.22"
          digest: "sha256:3a45f5bf323a03c9197ba47ef950e04e3c042f7e555cb6e04f92e2f768037975"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.14.22"
          target-environment: "QA"

