apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "26.10.38"
          url: "docker.io/cbpautomation/python-hello-world-docker:26.10.38"
          digest: "sha256:c3711e2fcb82fd7271639a4b8a5aaf43874e0bc4575b241623c465de58a3f811"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "26.10.38"
          digest: "sha256:c3711e2fcb82fd7271639a4b8a5aaf43874e0bc4575b241623c465de58a3f811"
          url: "docker.io/cbpautomation/python-hello-world-docker:26.10.38"
          target-environment: "QA"

