apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.23.59"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.23.59"
          digest: "sha256:cec44f64a85c5e7f514f7cf35a68994c14b859fe57c2a9e5a7832523f2e70657"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.23.59"
          digest: "sha256:cec44f64a85c5e7f514f7cf35a68994c14b859fe57c2a9e5a7832523f2e70657"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.23.59"
          target-environment: "QA"

