apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "15.11.56"
          url: "docker.io/cbpautomation/python-hello-world-docker:15.11.56"
          digest: "sha256:93e8cd7f8c2b6fc5c7280c44faa736651986e4a7769fbaf8869f9fc1dac61931"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "15.11.56"
          digest: "sha256:93e8cd7f8c2b6fc5c7280c44faa736651986e4a7769fbaf8869f9fc1dac61931"
          url: "docker.io/cbpautomation/python-hello-world-docker:15.11.56"
          target-environment: "QA"

