apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.43"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.43"
          digest: "sha256:f963d84a5866d502e97fea49542c9038c407c2101b52ba3f60316b97ee1344d2"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.43"
          digest: "sha256:f963d84a5866d502e97fea49542c9038c407c2101b52ba3f60316b97ee1344d2"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.43"
          target-environment: "QA"

