apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.10.41"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.10.41"
          digest: "sha256:e62c67d4847762ef875ae96c399b15c4aafce1e2ea4e4db5a4525932051a8f8f"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.10.41"
          digest: "sha256:e62c67d4847762ef875ae96c399b15c4aafce1e2ea4e4db5a4525932051a8f8f"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.10.41"
          target-environment: "QA"

