apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "07.10.54"
          url: "docker.io/cbpautomation/python-hello-world-docker:07.10.54"
          digest: "sha256:d0640d41a6fa9a56cb4d5c1be1ebc72a2a61ba30bbdc74b4a498b8bff15c74ca"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "07.10.54"
          digest: "sha256:d0640d41a6fa9a56cb4d5c1be1ebc72a2a61ba30bbdc74b4a498b8bff15c74ca"
          url: "docker.io/cbpautomation/python-hello-world-docker:07.10.54"
          target-environment: "QA"

