apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.14.26"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.14.26"
          digest: "sha256:b535822c7b597b952346f4b337382bd975d32f51a65666638841316589c470a9"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.14.26"
          digest: "sha256:b535822c7b597b952346f4b337382bd975d32f51a65666638841316589c470a9"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.14.26"
          target-environment: "QA"

