apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.10.05"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.10.05"
          digest: "sha256:f5c2a0bb249ec44608dad91b6fd05fc648e8351dce44592b7752952662a24d4e"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.10.05"
          digest: "sha256:f5c2a0bb249ec44608dad91b6fd05fc648e8351dce44592b7752952662a24d4e"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.10.05"
          target-environment: "QA"

