apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.11.58"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.11.58"
          digest: "sha256:2d046fe7009babf0ea5908bdfc99c85f06ff18cd46789d49fb73f18a9479c38a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.11.58"
          digest: "sha256:2d046fe7009babf0ea5908bdfc99c85f06ff18cd46789d49fb73f18a9479c38a"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.11.58"
          target-environment: "QA"

