apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "27.10.23"
          url: "docker.io/cbpautomation/python-hello-world-docker:27.10.23"
          digest: "sha256:6db72d47aa543284c350d03959e9d31f0ac089b109f4b71342adf90852e6e753"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "27.10.23"
          digest: "sha256:6db72d47aa543284c350d03959e9d31f0ac089b109f4b71342adf90852e6e753"
          url: "docker.io/cbpautomation/python-hello-world-docker:27.10.23"
          target-environment: "QA"

