apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.50"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.50"
          digest: "sha256:718961ae221a6143a57768799295b44f5358a41d809312e987c44dee2a8e80c9"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.50"
          digest: "sha256:718961ae221a6143a57768799295b44f5358a41d809312e987c44dee2a8e80c9"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.50"
          target-environment: "QA"

