apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.05.49"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.05.49"
          digest: "sha256:6fa5d972bcdd25463e4ab52aaef6ec95020ef44f15c8491bc4ab9828cb50a4af"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.05.49"
          digest: "sha256:6fa5d972bcdd25463e4ab52aaef6ec95020ef44f15c8491bc4ab9828cb50a4af"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.05.49"
          target-environment: "QA"

