apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.11.03"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.11.03"
          digest: "sha256:2bfb967d15f04c29c4cb63c954af23cf3ef70996c89828afe246fb61c055c298"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.11.03"
          digest: "sha256:2bfb967d15f04c29c4cb63c954af23cf3ef70996c89828afe246fb61c055c298"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.11.03"
          target-environment: "QA"

