apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.10.46"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.10.46"
          digest: "sha256:cf9ecaeb36db5b19b4353a2fdb6b7a2deab2ba07efba378e2db04a81efb83e25"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.10.46"
          digest: "sha256:cf9ecaeb36db5b19b4353a2fdb6b7a2deab2ba07efba378e2db04a81efb83e25"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.10.46"
          target-environment: "QA"

