apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.16"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.16"
          digest: "sha256:8662d4dc51e526e8524b28bbaa4cd1fd67eca52f8de0cd1d3484c41016a20c7d"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.16"
          digest: "sha256:8662d4dc51e526e8524b28bbaa4cd1fd67eca52f8de0cd1d3484c41016a20c7d"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.16"
          target-environment: "QA"

