apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.12.08"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.12.08"
          digest: "sha256:fa19dc99ab72b56d1d2d99386a38af90beb8e0a8a6b2fa2fd2669a6440bec183"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.12.08"
          digest: "sha256:fa19dc99ab72b56d1d2d99386a38af90beb8e0a8a6b2fa2fd2669a6440bec183"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.12.08"
          target-environment: "QA"

