apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.41"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.41"
          digest: "sha256:2c89b0fd0facac508094478202bd0456ed06a2c2020d249ebe3ffabb0636041e"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.41"
          digest: "sha256:2c89b0fd0facac508094478202bd0456ed06a2c2020d249ebe3ffabb0636041e"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.41"
          target-environment: "QA"

