apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.00.00"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.00.00"
          digest: "sha256:99ae3ad968bc02cb63194723a03f7eea1a611a2577b747babc19ac2ba2f45d9b"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.00.00"
          digest: "sha256:99ae3ad968bc02cb63194723a03f7eea1a611a2577b747babc19ac2ba2f45d9b"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.00.00"
          target-environment: "QA"

