apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.43"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.43"
          digest: "sha256:b73c524ae813672a9925f25447eb1bc9e1c5307d9fc40dfdb288319f82e1b030"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.10.43"
          digest: "sha256:b73c524ae813672a9925f25447eb1bc9e1c5307d9fc40dfdb288319f82e1b030"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.10.43"
          target-environment: "QA"

