apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.11.55"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.11.55"
          digest: "sha256:a50416f1ab2959c45ee12d1493a1460e1e39736fdd31d7fce9c1218c52b37b68"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.11.55"
          digest: "sha256:a50416f1ab2959c45ee12d1493a1460e1e39736fdd31d7fce9c1218c52b37b68"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.11.55"
          target-environment: "QA"

