apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.10.07"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.10.07"
          digest: "sha256:a9d592faff5b3ba2e088eeecd8d87b26d1ca1b1e7f752e3014e5b023603225b1"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.10.07"
          digest: "sha256:a9d592faff5b3ba2e088eeecd8d87b26d1ca1b1e7f752e3014e5b023603225b1"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.10.07"
          target-environment: "QA"

