apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.07"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.07"
          digest: "sha256:c556dfa8f5f5f2d13d84266fc71bb53c081fcde05808276b0f95435cc9c44fcb"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.07"
          digest: "sha256:c556dfa8f5f5f2d13d84266fc71bb53c081fcde05808276b0f95435cc9c44fcb"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.07"
          target-environment: "QA"

