apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.13"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.13"
          digest: "sha256:e2827cab13d52a69c20c9a7641f90551eb966c687850ee3ef20da1e039f72956"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.06.13"
          digest: "sha256:e2827cab13d52a69c20c9a7641f90551eb966c687850ee3ef20da1e039f72956"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.06.13"
          target-environment: "QA"

