apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.46"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.46"
          digest: "sha256:c8bca93219c7cf3aa0bc436f263753eb9e5adb37302b528fa0bcab3a20ec8170"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.10.46"
          digest: "sha256:c8bca93219c7cf3aa0bc436f263753eb9e5adb37302b528fa0bcab3a20ec8170"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.10.46"
          target-environment: "QA"

