apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-hello-world/.cloudbees/workflows/callable-workflow-461458fa-802b-4f83-b5d0-90cf1d06abb0.yaml
    