apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-helloworld/.cloudbees/workflows/callable-workflow-57fb6e95-ed23-4af2-8ef2-d8582f169dee.yaml
    