apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-helloworld/.cloudbees/workflows/callable-workflow-71f1b772-f773-4596-ba59-ffcddb1cd7a1.yaml
    