apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-hello-world/.cloudbees/workflows/callable-workflow-4eea39b4-067f-46ab-921c-7ed9004863f2.yaml
    