apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-hello-world/.cloudbees/workflows/callable-workflow-9bf9331d-aecf-402d-a7f4-8635684c694a.yaml
    