apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-helloworld/.cloudbees/workflows/callable-workflow-a3629478-b544-48dd-8c4a-57c1a55dc25c.yaml
    