apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-helloworld/.cloudbees/workflows/callable-workflow-4996ecbb-543c-4914-955b-ee7344f3fbe3.yaml
    